# Generated by Django 5.2.12 on 2026-04-20 12:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grace_period_minutes', models.PositiveIntegerField(default=0)),
                ('overdue_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('daily_max_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-is_active', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cash_shifts', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('OVERRIDE', 'Override')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('OVERRIDDEN', 'Overridden'), ('VOIDED', 'Voided')], default='CONFIRMED', max_length=20)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_tendered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('change_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('receipt_number', models.CharField(max_length=64, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cash_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.cashshift')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='parking.parkingsession')),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
