# Generated by Django 5.2.12 on 2026-04-20 12:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('zone_type', models.CharField(choices=[('VIP', 'VIP'), ('REGULAR', 'Regular'), ('RESERVED', 'Reserved')], default='REGULAR', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('SUV', 'SUV'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('BIKE', 'Motorbike'), ('OTHER', 'Other')], default='CAR', max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('OUT_OF_SERVICE', 'Out of service')], default='AVAILABLE', max_length=20)),
                ('is_manual_only', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkingzone')),
            ],
            options={
                'ordering': ['zone__priority', 'zone__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_PAYMENT', 'Pending payment'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grace_period_minutes', models.PositiveIntegerField(default=0)),
                ('extra_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('daily_max_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('manual_override_reason', models.TextField(blank=True)),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_sessions', to=settings.AUTH_USER_MODEL)),
                ('entry_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_sessions', to='camera.ocrscan')),
                ('exit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exit_sessions', to=settings.AUTH_USER_MODEL)),
                ('exit_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_sessions', to='camera.ocrscan')),
                ('manual_override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_exit_sessions', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='parking.parkingslot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='parking.vehicle')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='parkingslot',
            constraint=models.UniqueConstraint(fields=('zone', 'code'), name='unique_slot_per_zone'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'PENDING_PAYMENT'])), fields=('vehicle',), name='unique_active_vehicle_session'),
        ),
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'PENDING_PAYMENT'])), fields=('slot',), name='unique_active_slot_session'),
        ),
    ]
