# Generated by Django 5.2.12 on 2026-04-20 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='anpr/%Y/%m/%d')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('MANUAL', 'Manual')], default='ENTRY', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('candidate_plates', models.JSONField(blank=True, default=list)),
                ('detected_plate', models.CharField(blank=True, max_length=20)),
                ('confirmed_plate', models.CharField(blank=True, max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('manual_entry', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
