# Generated by Django 5.2.12 on 2026-04-20 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='GREEN', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-severity', '-created_at'],
            },
        ),
    ]
